"use client";

import { useState, useEffect } from "react";
import { createRecipe } from "@/app/actions/recipes";
import { RecipeForm, type RecipeFormDefaults } from "../_components/recipe-form";
import type { ImageStyleValue } from "@/lib/image-styles";
import { AiConcierge } from "../_components/ai-concierge";

interface NewRecipeClientProps {
  hasAi: boolean;
  defaultImageStyle?: ImageStyleValue;
}

export function NewRecipeClient({ hasAi, defaultImageStyle }: NewRecipeClientProps) {
  const [defaults, setDefaults] = useState<RecipeFormDefaults>({});
  const [formKey, setFormKey] = useState(0);

  // Pick up a draft generated by the AI Concierge page
  useEffect(() => {
    const stored = sessionStorage.getItem("ai_draft");
    if (!stored) return;
    sessionStorage.removeItem("ai_draft");
    try {
      const parsed = JSON.parse(stored) as RecipeFormDefaults;
      setDefaults(parsed);
      setFormKey((k) => k + 1);
    } catch {
      // ignore malformed draft
    }
  }, []);

  function handleRecipeGenerated(generated: RecipeFormDefaults) {
    setDefaults(generated);
    setFormKey((k) => k + 1);
  }

  return (
    <div className="space-y-6">
      {hasAi && (
        <div className="flex items-center justify-between rounded-lg border bg-muted/40 px-4 py-3">
          <p className="text-sm text-muted-foreground">
            Not sure what to cook? Let AI suggest ideas.
          </p>
          <AiConcierge onRecipeGenerated={handleRecipeGenerated} />
        </div>
      )}

      <RecipeForm
        key={formKey}
        action={createRecipe}
        defaults={defaults}
        heading="New Recipe"
        submitLabel="Create Recipe"
        mode="create"
        defaultImageStyle={defaultImageStyle}
      />
    </div>
  );
}
