"use client";

import { useState, useEffect } from "react";
import { createRecipe } from "@/app/actions/recipes";
import { RecipeForm, type RecipeFormDefaults } from "../_components/recipe-form";
import type { ImageStyleValue } from "@/lib/image-styles";
import { AiConcierge } from "../_components/ai-concierge";
import { PhotoImportModal } from "../_components/photo-import-modal";
import type { GeneratedRecipe } from "@/app/actions/ai";

interface NewRecipeClientProps {
  hasAi: boolean;
  defaultImageStyle?: ImageStyleValue;
}

export function NewRecipeClient({ hasAi, defaultImageStyle }: NewRecipeClientProps) {
  const [defaults, setDefaults] = useState<RecipeFormDefaults>({});
  const [formKey, setFormKey] = useState(0);

  // Pick up a draft generated by the AI Concierge page
  useEffect(() => {
    const stored = sessionStorage.getItem("ai_draft");
    if (!stored) return;
    sessionStorage.removeItem("ai_draft");
    try {
      const parsed = JSON.parse(stored) as RecipeFormDefaults;
      setDefaults(parsed);
      setFormKey((k) => k + 1);
    } catch {
      // ignore malformed draft
    }
  }, []);

  function handleRecipeGenerated(generated: RecipeFormDefaults) {
    setDefaults(generated);
    setFormKey((k) => k + 1);
  }

  function handlePhotoImport(recipe: GeneratedRecipe) {
    // GeneratedRecipe is structurally compatible with RecipeFormDefaults
    setDefaults(recipe as RecipeFormDefaults);
    setFormKey((k) => k + 1);
  }

  return (
    <div className="space-y-6">
      {hasAi && (
        <div className="rounded-xl border bg-gradient-to-r from-violet-500/10 via-purple-500/5 to-blue-500/10 px-4 py-3">
          <div className="flex flex-col sm:flex-row sm:items-center gap-3">
            <div className="flex-1">
              <p className="text-sm font-medium">AI Recipe Tools</p>
              <p className="text-xs text-muted-foreground mt-0.5">
                Scan a recipe photo, or let AI generate ideas from a prompt.
              </p>
            </div>
            <div className="flex items-center gap-2 flex-wrap">
              <PhotoImportModal onImport={handlePhotoImport} />
              <AiConcierge onRecipeGenerated={handleRecipeGenerated} />
            </div>
          </div>
        </div>
      )}

      <RecipeForm
        key={formKey}
        action={createRecipe}
        defaults={defaults}
        heading="New Recipe"
        submitLabel="Create Recipe"
        mode="create"
        defaultImageStyle={defaultImageStyle}
      />
    </div>
  );
}
